<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>CrosshairY</RootNamespace>
    <AssemblyName>CrosshairY</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>CrosshairY.ico</ApplicationIcon>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Fonts\**"/>
    <Resource Include="CrosshairY.ico"/>
  </ItemGroup>

</Project>